flowchart TD

subgraph Environment
AS[AppState: status == 'active'] --> AB[dispatch appBecameActive]
NI[NetInfo: passes offline  online] --> AC[dispatch appConnectivityChanged  online: true ]
end

subgraph appWl runtimeListener
AB --> N[outboxProcessOnce]
N --> O[replayRequested]
O --> P[syncDecideRequested]

AC --> R[outboxProcessOnce]
R --> S[syncDecideRequested]
end
